### ISSUE TITLE
Fatal error on install

### ISSUE THREAD

**Issue by danjjohnson** [woocommerce/sensei-certificates#130] opened 2017-06-02 15:34 UTC
User reports fatal error when installing for the first time:

> Fatal error: Class 'Woothemes_Sensei_Certificates_Utils' not found in .../wp-content/plugins/sensei-certificates/classes/class-woothemes-sensei-certificates-data-store.php on line 18

https://github.com/woocommerce/sensei-certificates/blob/f6e4168d7313e55e9e2dfb7786d71307b7c45c9d/classes/class-woothemes-sensei-certificates-data-store.php#L18

Presumably similar to this:
https://github.com/woocommerce/sensei-certificates/commit/f6e4168d7313e55e9e2dfb7786d71307b7c45c9d

585361-zd-woothemes
648604-zd-woothemes

Ping @pgk

**Comment by annezazu** [comment] 2017-06-18 19:02
@pgk repinging just in case :)

**Comment by gaurav1984** [comment] 2017-07-05 16:19
I can confirm that [302f80c](https://github.com/woocommerce/sensei-certificates/commit/302f80c4c93c93015bb094fd62adf88ecb8df219) fixes the bug.

Steps to reproduce the bug, on a new install of WordPress
1. Install Sensei
2. Import sample data
3. Install sensei-certificates plugin
4. On activation causes Fatal error

**Comment by gaurav1984** [comment] 2017-08-04 09:41
In 618454-zen the user is reporting that the issue is still happening.

They have Sensei v 1.9.16 & Sensei Certificates v 1.0.16 installed on their site.

**Comment by rachelsquirrel** [comment] 2017-08-08 08:17
Also reported in 612183-zen.

**Comment by gaurav1984** [comment] 2017-08-17 14:01
636366-zen

**Comment by gaurav1984** [comment] 2017-08-18 08:24
638651-zen

**Comment by dsmithweb** [comment] 2017-08-24 21:21
also 649713-zen

**Comment by deskroid** [comment] 2017-09-14 22:13
Hey guys! Any updates on this? This issue seems to be very much there - just because very few customers use it, there are not many tickets about it :)

**Comment by pgk** [comment] 2017-09-15 02:06
@deskroid The issue is fixed in #131 can you verify it fixes it for you?

**Comment by deskroid** [comment] 2017-09-15 02:07
Thanks! I have forwarded this to the customer. Will update here once they get back.

**Comment by davidcavalcante** [comment] 2017-09-25 06:22
Still waiting...

**Comment by deskroid** [comment] 2017-09-25 07:19
The customer hasn't replied yet and the ticket is auto-closed at this time. Let's close this issue as Solved - if the customer comes back, we will re-open. I have tested this myself and it works so I guess we should be fine 👍

**Comment by davidcavalcante** [comment] 2017-09-25 07:21
It does not work for me. It is giving the same error, and I have the updated versions of Sensei and Wordpress. This error is causing me SERIOUS problems. I really need the solution.
Thanks!

**Comment by davidcavalcante** [comment] 2017-09-25 07:21
Can you give me the solution to the problem?

**Comment by PDowney** [comment] 2017-09-25 17:47
It's probably time to start looking at another LMS. WooCommerce isn't focusing on Sensei much at all and it's lagged behind feature wise. Certificates is a huge feature that is totally ignored and currently broken for many.  

I'm already in the process of moving my large site off of Sensei.

**Comment by davidcavalcante** [comment] 2017-09-26 08:30
That sucks! Because we buy Sensei... Do you recommend something else that works with Woocommerce (Wordpress)?

**Comment by rachelsquirrel** [comment] 2017-09-26 15:59
@davidcavalcante Did you try the fix here https://github.com/woocommerce/sensei-certificates/pull/131 ? 

If you tried that and it didn't work can you please open a ticket with us so we can take a closer look at your site? You can submit a ticket through our website at https://woocommerce.com/contact-us/.

**Comment by davidcavalcante** [comment] 2017-09-26 17:00
Work, thanks!

**Comment by aheckler** [comment] 2017-10-16 19:05
734450-zen

**Comment by aheckler** [comment] 2017-10-17 19:28
741362-zen

**Closed** 2017-10-24 14:43 UTC
Labels: bug
