### ISSUE TITLE
Duplicate certificates for multiple students

### ISSUE THREAD

**Issue by PDowney** [woocommerce/sensei-certificates#123] opened 2017-04-17 22:03 UTC
After the last update, certificates are no longer auto-generating on course completion. When I ran the manual update with Sensei, it made a new certificate for those students that were missing the certificate, but they all had the same exact hash ID, certificate title, student name, completion date. meaning, when viewing the certificate for john smith's widget 1 course, his certificate would instead show jane doe's widget 2 course certificate instead. Something got very broken with the most recent commit.

**Comment by PDowney** [comment] 2017-04-17 23:23
After playing with some different commits for this and Sensei itself, I'm also seeing certificates generate in triples for a single course. After completing a course, 3 of the same certificate with the same hash ID are created.

**Comment by danjjohnson** [comment] 2017-04-21 13:13
The triple (or sometimes double) certificates is a duplicate of #118 

I'm not seeing any issues with certificates not auto-generating though. Have you tested the 1.0.14 beta release?
https://github.com/woocommerce/sensei-certificates/releases/tag/version%2F1.0.14-beta

**Comment by pgk** [comment] 2017-04-28 14:27
fixed in 	5b01c06 ref #118

**Closed by pgk** 2017-04-28 14:27 UTC
