### ISSUE TITLE
Special characters not displaying in PDFs when using a filter

### ISSUE THREAD

**Issue by aheckler** [woocommerce/sensei-certificates#91] opened 2016-03-22 14:08 UTC
When I use this code to change the date format:

``` php
add_filter( 'sensei_certificate_date_format', 'sensei_reorder_certificate_date' );

function sensei_reorder_certificate_date() {
    $date_format = '%e %B %Y';
    return $date_format;
}
```

... and then view a cert with my site set to the Portuguese language, I see this:

![screen shot 2016-03-22 at 10 06 34 am](https://cloud.githubusercontent.com/assets/5512652/13954116/c70b7fc0-f015-11e5-8407-ec448ea8e3be.png)

Possible related to (or a dupe of) #24? Was it reintroduced somehow?

399674-zd-woothemes

**Comment by diogenesjup** [comment] 2017-04-16 23:50
Any solutions for this problem?

**Comment by danjjohnson** [comment] 2017-04-19 15:36
We don't have a solution for this at the moment. I would suggest using a date format with numbers only for the time being.

**Comment by donnapep** [comment] 2018-06-14 19:44
To reproduce, ensure you're viewing the certificate on the front-end and not in WordPress admin.

**Comment by alexsanford** [comment] 2018-07-19 18:54
I cannot reproduce this. There are two issues:

- Running this as-is does not do any translation for me. I just get the month name in English.
- Running this using the [newly date format syntax](https://github.com/woocommerce/sensei-certificates/pull/150), with the format string `'j F Y'`, I have no problem with characters displaying:

![image](https://user-images.githubusercontent.com/842193/42963748-84605d32-8b6b-11e8-9c3a-41e70357ebc5.png)

**Comment by alexsanford** [comment] 2018-07-23 20:20
Removing this from the milestone, because I cannot reproduce the issue.

@donnapep if you can still reproduce this, go ahead and add it to the next milestone with some more detailed instructions.

**Comment by donnapep** [comment] 2018-07-31 19:40
I can reproduce this without issue on my sandbox using either Portuguese or German and previewing a certificate with a March date. When I remove the filter code, the special characters show without issue, so it does not appear to be a problem with fonts.

If reproducing is still a problem, let me know and I can create an admin account on my sandbox.

**Comment by alexsanford** [comment] 2018-07-31 20:05
@donnapep After our discussion, I was also able to reproduce this on my sandbox. A few notes on reproducing the issue:

- You have to use the `%`-style date format specifiers to force it to use `strftime`. The problem does not exist when using the WP `date_i18n` function (see https://github.com/woocommerce/sensei-certificates/pull/150).

- `strftime` uses system settings to translate the strings. I was not able to reproduce this on my local environment because I did not have the locales installed, so `strftime` simply did not do any translation at all.

Given that https://github.com/woocommerce/sensei-certificates/pull/150 is landing in 1.1.0, I would argue that this issue is a `wontfix`, and any new code should simply use the supported format strings compatible with `date_i18n`.

**Comment by donnapep** [comment] 2018-08-01 12:35
@alexsanford I'm not quite sure I follow why you think we shouldn't fix this. What about sites that are currently using the filter with formats similar to `'%e %B %Y'`?

**Comment by alexsanford** [comment] 2018-08-02 00:37
@donnapep My argument would be that from 1.1.0 onward, the supported way to format dates is using a format string supported by `date_i18n`. If sites are currently using a filter to set the format to `%e %B %Y` it should be a simple matter to change it to something like `j F Y`. For sites that are not using a filter, the default format string will be automatically changed to match the WP Settings (i.e. it's already fixed for those not using the filter).

The only reason I wanted to continue to support the `stftime`-style format strings in #150 was so that we didn't _break existing sites_ that were using those strings. But in the case of this bug, the PDFs generated when using those strings were _already broken_. I think that for sites affected by this bug, changing the format string in the filter is a perfectly fine solution 🙂 

That said, if you think we should still try to fix this, then I'm guessing we'll have to dig into:

- Figuring out the strings that are coming back from `strftime`. This may be system-dependent.
- Looking into the PDF-generation library to see why it's tripping on those characters. Maybe it's some sort of Unicode support mismatch?

**Comment by donnapep** [comment] 2018-08-02 12:01
Given the fact that this was already broken, that it would likely require a not insignificant amount of effort to fix and that there's an available workaround, I'm closing this issue.

The workaround for those using the `sensei_certificate_date_format ` filter with a format string similar to `%e %B %Y` is to use one of the [supported formats](https://codex.wordpress.org/Formatting_Date_and_Time).

**Closed by donnapep** 2018-08-02 12:01 UTC
Labels: [Pri] Normal, [Status] Accepted, [Type] Bug
