### ISSUE TITLE
CRITICAL Uncaught Error: Call to undefined function Sensei()

### ISSUE THREAD

**Issue by AiratHalitov** [woocommerce/sensei-certificates#144] opened 2018-05-10 09:53 UTC
I found this error in WooCommerce error log

```
2018-04-12T15:34:41+00:00 CRITICAL Uncaught Error: Call to undefined function Sensei() in /my_path/wp-content/plugins/sensei-certificates/classes/class-woothemes-sensei-certificates.php:88
Stack trace:
#0 /my_path/wp-content/plugins/sensei-certificates/woothemes-sensei-certificates.php(69): WooThemes_Sensei_Certificates->__construct('/home/admin/web...')
#1 /my_path/wp-includes/class-wp-hook.php(286): init_sensei_certificates('')
#2 /my_path/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /my_path/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /my_path/wp-settings.php(327): do_action('plugins_loaded')
#5 /my_path/wp-config.php(123): require_once('/home/admin/web...')
#6 /my_path/wp-load.php(37): require_once('/home/admin/web...')
#7 /my_path/wp-admin
```

There are four similar errors in 

- 2018-04-12T15:34:41+00:00
- 2018-04-12T15:34:44+00:00
- 2018-04-12T15:34:46+00:00
- 2018-04-12T15:34:52+00:00

### Configuration: 
- WordPress 4.9.5
- WooCommerce 3.3.5
-  BuddyPress 2.9.4
- BuddyPress for Sensei 1.2.1
- Sensei 1.10.1
- Sensei Certificates 1.0.17

**Comment by donnapep** [comment] 2018-06-14 20:05
@AiratHalitov I'm not able to reproduce this one. Could you include steps to follow in order to generate this error? Thx!

**Comment by AiratHalitov** [comment] 2018-06-15 08:10
I don't know how to reproduce this error. 
I found this error in the WC logs.

**Comment by donnapep** [comment] 2018-06-15 10:35
Thanks. I'll have to close this issue then, but will keep an eye on the logs. Cheers!

**Closed by donnapep** 2018-06-15 10:35 UTC
Labels: [Status] Needs Author Reply
