### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function Sensei() in /var/www/html/wp-content/plugins/sensei-certificates/classes/class-woothemes-sensei-certificates.php:88

### ISSUE THREAD

**Issue by lvnilesh** [woocommerce/sensei-certificates#137] opened 2017-11-06 00:57 UTC
```
[06-Nov-2017 00:57:01 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Sensei() in /var/www/html/wp-content/plugins/sensei-certificates/classes/class-woothemes-sensei-certificates.php:88
Stack trace:
#0 /var/www/html/wp-content/plugins/sensei-certificates/woothemes-sensei-certificates.php(69): WooThemes_Sensei_Certificates->__construct('/var/www/html/w...')
#1 /var/www/html/wp-includes/class-wp-hook.php(298): init_sensei_certificates('')
#2 /var/www/html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#3 /var/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /var/www/html/wp-settings.php(325): do_action('plugins_loaded')
#5 /var/www/html/wp-config.php(112): require_once('/var/www/html/w...')
#6 /var/www/html/wp-load.php(37): require_once('/var/www/html/w...')
#7 /var/www/html/wp-cron.php(26): require_once('/var/www/html/w...')
#8 {main}
  thrown in /var/www/html/wp-content/plugins/sensei-certificates/classes/class-woothemes-sensei-certificates.php on line 88
```

**Comment by donnapep** [comment] 2018-06-15 19:20
Closing as I'm not able to reproduce this error.

**Closed by donnapep** 2018-06-15 19:20 UTC
