### ISSUE TITLE
PHP Fatal error on install

### ISSUE THREAD

**Issue by ubcshen** [woocommerce/sensei-certificates#132] opened 2017-07-19 17:44 UTC
trying to install this plugin with Sensei 1.7.4. and we are getting "Plugin could not be activated because it triggered a fatal error.
Fatal error: Class 'Sensei_Utils' not found in /wp-content/plugins/sensei-certificates/woothemes-sensei-certificates.php on line 208
"

**Comment by ubcshen** [comment] 2017-07-19 21:28
also PHP Fatal error: Call to undefined function Sensei() in /wp-content/plugins/sensei-certificates/classes/class-woothemes-sensei-certificates.php on line 88

**Comment by danjjohnson** [comment] 2017-07-20 07:30
@ubcshen try using the latest Sensei version (1.9.16)

**Comment by DHWP** [comment] 2017-08-17 13:03
I'm using 1.9.16 and having the same fatal error.

Plugin could not be activated because it triggered a fatal error.
Fatal error: Uncaught Error: Class 'Woothemes_Sensei_Certificates_Utils' not found

**Comment by ricsmo** [comment] 2017-08-24 05:54
I'm receiving the same error, also running 1.9.16 on PHP 7.1

Adding this if statement at least got it to install. Not sure if there are still problems elsewhere.
/classes/class-woothemes-sensei-certificates-data-store.php starting at line 17

`    function insert( $user_id, $course_id ) {
	    if ( !class_exists('Woothemes_Sensei_Certificates_Utils') ) {
		    include_once( 'class-woothemes-sensei-certificates-utils.php' );
	    }
        $certificate_hash = Woothemes_Sensei_Certificates_Utils::get_certificate_hash( $course_id, $user_id );
...`

**Comment by pgk** [comment] 2017-09-26 10:16
closing as duplicate of #130

**Closed by pgk** 2017-09-26 10:16 UTC

**Comment by joul** [comment] 2019-04-23 11:03
I ran into the some error

**Comment by richardmtl** [comment] 2019-04-23 14:37
@joul Please contact us [here](https://woocommerce.com/my-account/create-a-ticket/) for support with this; this issue is 2 years old and likely isn't the exact same problem.

**Comment by joul** [comment] 2019-04-23 16:44
> I ran into the some error

i have managed to resolve it after installing "Sensei" plugin
