### ISSUE TITLE
Create ability to lock down certificate

### ISSUE THREAD

**Issue by annezazu** [woocommerce/sensei-certificates#138] opened 2017-12-23 17:18 UTC
Right now, a certificate is re-generated each time you complete the course over again. As a result, you can reset a lesson and complete it over again and the date on the course certificate will update.

We should add an option to "lock in" the certificate date.

**Comment by donnapep** [comment] 2018-06-15 19:08
Closing as duplicate of #32.

**Closed by donnapep** 2018-06-15 19:08 UTC
