### ISSUE TITLE
Course text is too long

### ISSUE THREAD

**Issue by vinvin27** [woocommerce/sensei-certificates#273] opened 2021-08-09 21:10 UTC
The tag {{course_title}} is too long on our case even is a reduce the size of the content on the template its overflow.

How to deal with it ?

![Capture d’écran 2021-08-09 à 17 07 07](https://user-images.githubusercontent.com/3788327/128774860-fb2c43f5-34ff-4369-bab9-667aed34a0ec.png)

**Comment by alexsanford** [comment] 2021-08-20 16:30
One option would be to edit the Certificate Template being used and change the font size for that section. On my site, the "Course" section of the template looks like this:

<img width="1182" alt="Screen Shot 2021-08-20 at 13 21 34" src="https://user-images.githubusercontent.com/842193/130263804-e0f9f8ec-2b65-4048-ac05-2f98dcf213c8.png">

Adjusting the font size down allows for longer Course titles.

Closing this for now as questions like this would be better suited for the [support forum](https://wordpress.org/support/plugin/sensei-certificates/). Please feel free to raise another issue with a reproducible bug or specific feature request 🙂

**Closed by alexsanford** 2021-08-20 16:30 UTC
Labels: [Type] Bug
